name: Microservice Deployment Logic

on:
  workflow_dispatch:
    inputs:
      serviceOne:
        description: "Service 1"
        type: boolean
      serviceTwo:
        description: "Service 2"
        type: boolean
      environmentServiceOne:
        description: "Service 1 Deployment Environment"
        type: choice
        options:
          - service1_prod
          - service1_dev
      environmentServiceTwo:
        description: "Service 2 Deployment Environment"
        type: choice
        options:
          - service2_prod
          - service2_dev

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - run: echo "Unit Tests"
        shell: bash

  service_one_deployment:
    if: inputs.serviceOne == true
    needs: unit_tests
    environment: ${{ inputs.environmentServiceOne }}
    runs-on: ubuntu-latest
    name: Service 1
    steps:
      - run: |
          if [[ "${{ inputs.environmentServiceOne }}" == "service1_prod" ]]; then
            MSG="Going to prod!"
          elif [[ "${{ inputs.environmentServiceOne }}" == "service1_dev" ]]; then
            MSG="Going to dev!"
          else
            MSG="Unknown environment!"
          fi
          echo "$MSG"
        shell: bash

  service_two_deployment:
    if: inputs.serviceTwo == true
    needs: unit_tests
    environment: ${{ inputs.environmentServiceTwo }}
    runs-on: ubuntu-latest
    name: Service 2
    steps:
      - run: echo "Service 2"
        shell: bash 
