
name: Microservice Deployment Logic - On Merge

on:
 pull_request:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - run: echo "Unit Tests"
        shell: bash

  service_one_deployment:
    needs: unit_tests
    environment: service1_prod
    runs-on: ubuntu-latest
    name: Service 1 Deployment
    steps:
      - run: echo "Service 1"
        shell: bash

  service_two_deployment:
    needs: unit_tests
    environment: service2_prod
    runs-on: ubuntu-latest
    name: Service 2 Deployment
    steps:
      - run: echo "Service 2"
        shell: bash 
